### ISSUE TITLE
Z Grid Plane doesn't move with model size changes

### ISSUE THREAD

**Issue by grking** [grking/zoxel#32]
When the voxel space expands along the Z axis, the Z grid plane doesn't move with it.

This is because it's offset is set relative to 0, so as the depth increases the grid never knows about it.

Could make the Z plane grid offset relative to "depth" rather than zero....

**Comment by brunocanella** [comment]
Ops... I forgot about the auto-expanding functionality :open_mouth: 

I will fix that later in this or the next week.

I'm currently working in an interface for the users to be able to add their own custom grids to the environment, but since I will have a Calculus 3 exam next week, I won't be able to work that much on the Zoxel project.

By the way, you have a really nice open-source project here. I hope more people join the cause soon :smile:.

We are using your tool right now to create the models for our game, and since we are adopting a policy of using only open-source software, we decided to contribute to this project while we develop ours.

**Comment by grking** [comment]
Glad you are finding a use for it.  Thanks for your contributions. :)

**Comment by brunocanella** [comment]
Thank you for making this an open-source project :D

**Comment by grking** [comment]
Fixed by ac7ed6bcf7e955f9a76562cf1301f70a56572818
